"""add post enums

Revision ID: 27a48ca54d30
Revises: 973dc2a05f40
Create Date: 2026-09-03 14:11:04.614596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a48ca54d30'
down_revision: Union[str, Sequence[str], None] = '973dc2a05f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'category',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('DISCUSSION', 'RECOMMENDATION', 'EVENT', 'SERVICE', 'LOST_FOUND', 'ISSUE', 'ALERT', name='post_category'),
               existing_nullable=False)
    op.alter_column('posts', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PUBLIC', 'NEIGHBORHOOD', name='post_visibility'),
               existing_nullable=False)
    op.alter_column('posts', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'HIDDEN', 'DELETED', name='post_status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'status',
               existing_type=sa.Enum('ACTIVE', 'HIDDEN', 'DELETED', name='post_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('posts', 'visibility',
               existing_type=sa.Enum('PUBLIC', 'NEIGHBORHOOD', name='post_visibility'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('posts', 'category',
               existing_type=sa.Enum('DISCUSSION', 'RECOMMENDATION', 'EVENT', 'SERVICE', 'LOST_FOUND', 'ISSUE', 'ALERT', name='post_category'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
