"""create neighborhoods table

Revision ID: 842bfdbc255d
Revises: 9d3f22ad5d0b
Create Date: 2026-09-04 20:15:04.671895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842bfdbc255d'
down_revision: Union[str, Sequence[str], None] = '9d3f22ad5d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neighborhoods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_neighborhoods_city'), 'neighborhoods', ['city'], unique=False)
    op.create_index(op.f('ix_neighborhoods_id'), 'neighborhoods', ['id'], unique=False)
    op.create_index(op.f('ix_neighborhoods_name'), 'neighborhoods', ['name'], unique=True)
    op.create_index(op.f('ix_neighborhoods_slug'), 'neighborhoods', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_neighborhoods_slug'), table_name='neighborhoods')
    op.drop_index(op.f('ix_neighborhoods_name'), table_name='neighborhoods')
    op.drop_index(op.f('ix_neighborhoods_id'), table_name='neighborhoods')
    op.drop_index(op.f('ix_neighborhoods_city'), table_name='neighborhoods')
    op.drop_table('neighborhoods')
    # ### end Alembic commands ###
